mutation MoveMainTask($input: MoveMainTaskInput!) {
    moveMainTask(input: $input) {
        board {
            id
            name
            columns {
                id
                name
                mainTasks {
                    description
                    id
                    status
                    title
                    subTasks {
                        id
                        isCompleted
                        title
                    }
                }
            }
        }
    }
}
