on:
  push:
    branches:
      - main
name: 'KabanFrontCi'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Clean files on Remote Server'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf ${{ secrets.APP_PATH }}

      - name: 'Build the Docker image'
        run: docker build . -t kaban-front:latest

      - name: 'Save Docker image as tar file'
        run: |
          docker save -o kaban-front.tar kaban-front:latest
          chmod 666 ./kaban-front.tar

      - name: 'Transfer Docker Compose file to remote server'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./kaban-front.tar"
          target: ${{ secrets.APP_PATH }}
          overwrite: true

      - name: 'Load Docker image on remote server'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker load -i ${{ secrets.APP_PATH }}/kaban-front.tar

      - name: 'Transfer Docker Compose file to remote server'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./docker-compose.yaml"
          target: ${{ secrets.APP_PATH }}
          strip_components: 1
          overwrite: true

      - name: 'Deploy Docker containers using Docker Compose on remote server'
        uses: appleboy/ssh-action@v1.0.3
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: SHA
          debug: true
          script: |
            docker compose -f ${{ secrets.APP_PATH }}/docker-compose.yaml up -d